[package]
name = "delegation-mock-meta"
version = "0.0.1"
authors = ["CleiK"]
edition = "2018"
publish = false

[dependencies.delegation-mock]
path = ".."

[dependencies.elrond-wasm]
version = "0.30.0"

[dependencies.elrond-wasm-debug]
version = "0.30.0"
